### ISSUE TITLE
 Error: The hook `userconfig`

### ISSUE THREAD

**Issue by socialwarespace** [Hylozoic/hylo-node#446]
#npm run dev

> hylo-node@1.0.0 dev /Users/*****/Downloads/hylo-node-master
> nf -j Procfile.dev -p 3001 start -t 1000

[OKAY] Loaded ENV .env File as KEY=VALUE Format
[OKAY] Trimming display Output to 1000 Columns
09:45:01 worker.1   |  [nodemon] 1.12.1
09:45:01 worker.1   |  [nodemon] to restart at any time, enter `rs`
09:45:01 worker.1   |  [nodemon] watching: *.*
09:45:01 worker.1   |  [nodemon] starting `node worker.js --delay=0.5`
09:45:01 web.1      |  [nodemon] 1.12.1
09:45:01 web.1      |  [nodemon] to restart at any time, enter `rs`
09:45:01 web.1      |  [nodemon] watching: *.*
09:45:01 web.1      |  [nodemon] starting `node --inspect=3001 app.js --delay=0.5`
09:45:01 web.1      |  Debugger listening on ws://127.0.0.1:3001/aa50c30c-c426-415f-859f-0ecd84d4dd1c
09:45:01 web.1      |  For help see https://nodejs.org/en/docs/inspector
09:45:03 web.1      |  info: Lifting...
09:45:08 web.1      |  Successful api response. Link: https://rollbar.com/occurrence/uuid/?uuid=185d6c79-4237-435d-9436-1411da828f65
09:45:10 worker.1   |  info: Lifting...
09:45:13 worker.1   |  Successful api response. Link: https://rollbar.com/occurrence/uuid/?uuid=3afbaa51-b5ec-4892-c16e-ac53954bad68
09:46:25 web.1      |  error: Error: The hook `userconfig` is taking too long to load.
09:46:25 web.1      |  Make sure it is triggering its `initialize()` callback, or else set `sails.config.userconfig._hookTimeout to a higher value (currently 80000)
09:46:25 web.1      |      at Timeout.tooLong [as _onTimeout] (/Users/*****/Downloads/hylo-node-master/node_modules/sails/lib/app/private/loadHooks.js:85:21)
09:46:25 web.1      |      at ontimeout (timers.js:469:11)
09:46:25 web.1      |      at tryOnTimeout (timers.js:304:5)
09:46:25 web.1      |      at Timer.listOnTimeout (timers.js:264:5)
09:46:31 worker.1   |  Couldn't lift Sails: Error: The hook `userconfig` is taking too long to load.
09:46:31 worker.1   |  Make sure it is triggering its `initialize()` callback, or else set `sails.config.userconfig._hookTimeout to a higher value (currently 80000)
09:46:31 worker.1   |  Error: The hook `userconfig` is taking too long to load.
09:46:31 worker.1   |  Make sure it is triggering its `initialize()` callback, or else set `sails.config.userconfig._hookTimeout to a higher value (currently 80000)
09:46:31 worker.1   |      at Timeout.tooLong [as _onTimeout] (/Users/socialware/Downloads/hylo-node-master/node_modules/sails/lib/app/private/loadHooks.js:85:21)
09:46:31 worker.1   |      at ontimeout (timers.js:469:11)
09:46:31 worker.1   |      at tryOnTimeout (timers.js:304:5)
09:46:31 worker.1   |      at Timer.listOnTimeout (timers.js:264:5)
09:46:31 worker.1   |  [nodemon] app crashed - waiting for file changes before starting...

**Comment by vikaskulkarni** [comment]
I am also extremely frustrated with this issue. Tried all possible ways to increase the timeout by putting in several different ways. But this error doesn't seem to go away. Please do let me know if you have a way to fix.
The things I tried;
1. created a file development.js and put the below. created a new file userconfig.js inside config folder and put the below
`module.exports = {
  hookTimeout: 120000, // 2 minutes
};
module.exports = {
  _hookTimeout: 120000, // 2 minutes
};
`
3. tried sails_config__userconfig__hookTimeout in package.json environment
